# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - haalnuaf-website

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: create env
      run: |
        echo $'VUE_APP_SALT=A1130376DC52759858000B8CA72A2C72BF89FE0EA37866AED6D9DCCDD443C3EA\nVUE_APP_API=https://prod-api.haalnuaf.nl' > .env
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'haalnuaf-website'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f01cce2a83284724abea6cbc145f3d20 }}
        package: .
